extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
  - prettier
env:
  es6: true
  browser: true
globals:
  expect: true
  it: true
parser: babel-eslint
rules:
  strict: 0
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: none
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  import/no-extraneous-dependencies: 0
