extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
  - prettier
env:
  es6: true
  browser: true
globals:
  AFRAME: true
  it: true
parser: babel-eslint
rules:
  strict: 0
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: none
