version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7.0
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - type: deploy
        name: Deploy project.
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "this will deploy"
          fi
